language: node_js
node_js:
  - "4.1"
install:
  - npm install gitbook-cli markdown-spellcheck -g
script:
  - gitbook install
  - gitbook build
  - mdspell '**/*.md' '!**/node_modules/**/*.md' '!**/_book/**/*.md' --ignore-numbers --report
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: _book
  fqdn: docs-origin.telemetry.mozilla.org
  on:
    branch: master
