language: rust
addons:
  apt:
    packages:
      - parallel
install:
  - npm install markdown-spellcheck markdown-link-check -g
  - curl -LSfs https://japaric.github.io/trust/install.sh | sh -s -- --git rust-lang-nursery/mdBook
  - curl -LSfs https://japaric.github.io/trust/install.sh | sh -s -- --git badboy/mdbook-toc
  - curl -LSfs https://japaric.github.io/trust/install.sh | sh -s -- --git badboy/mdbook-mermaid
script:
  - mdbook --version
  - mdbook-toc --version
  - mdbook-mermaid --version
  - mdbook build .
  - bash scripts/spell_check.sh
  - bash scripts/link_check.sh
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: book
  fqdn: docs-origin.telemetry.mozilla.org
  on:
    branch: master
