language: node_js
node_js:
  - "4.1"
addons:
  apt:
    packages:
      - parallel
install:
  - npm install gitbook-cli markdown-spellcheck markdown-link-check -g
script:
  - gitbook install
  - gitbook build
  - mdspell '**/*.md' '!**/node_modules/**/*.md' '!**/_book/**/*.md' --ignore-numbers --en-us --report
  - bash scripts/link_check.sh
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: _book
  fqdn: docs-origin.telemetry.mozilla.org
  on:
    branch: master
